Add `-headerpad_max_install_names` to macOS linker flags
Travis CI macOS build started failing on [2024-12-28][1].
```
error: /Applications/Xcode-14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: test_aes_in_ecb_mode (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)
```
Not quite sure of the trigger cause.

[1]: https://app.travis-ci.com/github/tanzislam/cryptopals/jobs/629344691#L2327